### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kassane** [kassane/zig-xlsxwriter#1]
This is only an initial foundation which will need improvement.
The original api made by @jmcnamara I' m still reading. [#245](https://github.com/jmcnamara/libxlsxwriter/issues/245)

### TODO

- [x] More examples
- [ ] improvement wrapper (binding)
- [ ] turn wrapper on port.

### Issue

- [x] https://github.com/ziglang/zig/issues/13468#issuecomment-1328097092

provisional solution:

add `struct_headname` `opaque` type.
https://github.com/kassane/zig-xlsxwriter/blob/2d300722f5fbf9dbe70cb8065e6bb59f66e77aa4/src/xlsxwriter.zig#L2564

**Comment by jmcnamara** [comment]
> The original api made by @jmcnamara I' m still reading.

Best of luck with this.

**Comment by kassane** [comment]
> > The original api made by @jmcnamara I' m still reading.
> 
> Best of luck with this.

Thanks!

It is interesting how rust ported the original C code is like this.
At this exact moment I' m translating some examples (not all of them) and just want to turn the initial wrapper into a zig-port.

**Comment by awesomo4000** [comment]
Hi Kassane ... I ported all of the examples and everything builds on my MacOS machine.. my build is a bit different and there are some verification tools in there for examining the excel files and screenshotting the outputs for ease of comparison. I had to rewrite history due to some miscommits but feel free to take whatever .. 

https://github.com/awesomo4000/zig-xlsxwriter/tree/main/examples

**Comment by kassane** [comment]
> I ported all of the examples and everything builds... my build is a bit different and there are some verification tools in there for examining the excel files and screenshotting the outputs for ease of comparison.

Wow. Amazing!

>  I had to rewrite history due to some miscommits but feel free to take whatever

Thanks.

**Comment by awesomo4000** [comment]
Turns out it builds fine on Windows 11 (aarch64) as well .. didn't have to change anything.

**Comment by 0x546F6D** [comment]
Hi @kassane, do you have any specific plan to implement the goals mentioned in the 1st post for this wrapper, or is it on hold for now?

I am asking because I originally only forked this repo to update the build.zig.zon according to 0.14 standards.
But then I decided to modify build.zig in order to use addTranslateC(), since @cImport is planned to be deprecated, as well as usingnamespace for incremental compilation.
Afterwards, I got curious, looked at errors.zig and once again decided to update it as well. And while I was at it, I decided to use it too..

1 thing let to the other and I ended up wrapping a bunch of libxlsxwriter functions for fun, while rewriting your 4 examples in order to make them feel more "zig-like" to me.

for example, here is what the main() of tutorial2.zig turned into:
```zig
    // Create a workbook and add a worksheet.
    const workbook = try xlsxwriter.WorkBook.init("out/tutorial2.xlsx");
    const worksheet = try workbook.addWorkSheet(null);

    // Start from the first cell. Rows and columns are zero indexed.
    var row: u32 = 0;
    const col: u16 = 0;

    // Add a bold format to use to highlight cells.
    const bold = try workbook.addFormat();
    bold.setBold();

    // Add a number format for cells with money.
    const money = try workbook.addFormat();
    money.setNumFormat("$#,##0");

    // Add an Excel date format.
    const date_format = try workbook.addFormat();
    date_format.setNumFormat("mmmm d yyyy");

    // Adjust the column width.
    try worksheet.setColumn(
        0,
        0,
        15,
        .none,
    );

    // Write some data header.
    try worksheet.writeString(
        row,
        col,
        "Item",
        bold,
    );
    try worksheet.writeString(
        row,
        col + 2,
        "Cost",
        bold,
    );

    // Iterate over the data and write it out element by element.
    for (&expenses) |*expense| {
        row += 1;
        try worksheet.writeString(
            row,
            col,
            expense.item,
            .none,
        );
        try worksheet.writeDateTime(
            row,
            col + 1,
            &expense.datetime,
            date_format,
        );
        try worksheet.writeNumber(
            row,
            col + 2,
            expense.cost,
            money,
        );
    }
    row += 1;

    // Write a total using a formula.
    try worksheet.writeString(
        row,
        col,
        "Total",
        .none,
    );
    try worksheet.writeFormula(
        row,
        col + 2,
        "=SUM(C2:C5)",
        .none,
    );

    // Save the workbook and free any allocated memory.
    try workbook.deinit();
```

I am planning to continue working on it by converting @awesomo4000's great list of examples, which should help me wrap up pretty much every functions/const/enum/..

However, before making any PR, I would like to know if the way I am currently going, is also the direction you had in mind for this repo. If you want to have a look at the src:
https://github.com/0x546F6D/zig-xlsxwriter/tree/main/src

**Comment by kassane** [comment]
Hi @0x546F6D ,

I had a quick look at your changes. I found them interesting too.

Unfortunately, I left out some projects. This is one of them.
The intention was to rewrite it instead of the Zig-like wrapper. However, focus was lost on this project.

You are welcome to submit a PR. You also have the option to create an independent fork.

I would like to express my gratitude to @jmcnamara for enabling and embracing the incorporation of `build.zig` support into the upstream project.

**Comment by 0x546F6D** [comment]
I understand. I used rust_xlsxwriter in the past and was really glad to find libxlsxwriter, especially with the adoption of your build.zig upstream, which makes it a breeze to use directly with zig.

Since this repo is the 1st result when looking for zig+xlsxwriter, I'll prepare a PR once I finish going through all the examples provided by @awesomo4000.
Unless @jmcnamara decides to create an official repo for a zig_xlsxwriter wrapper(?), to add to his collection of supported languages after python/rust/perl/lua, in which case I would contribute to that repo instead.

**Comment by awesomo4000** [comment]
Heya -- we should team up. I have a good start on a zig friendly wrapper
and about half the examples done for it. I'll check it in later today and
you can see what it looks like.

(Awesomo4000)

**Comment by jmcnamara** [comment]
> Unless [@jmcnamara](https://github.com/jmcnamara) decides to create an official repo for a zig_xlsxwriter wrapper

I usually prefer to do a pure port to a new language. This often coincides with using or evaluating a new language for work. However, at the moment I don't have any plans to start a pure Zig port (although I am interested in the language). I'm not currently finished with the Rust port yet and the Python port needs a lot of type annotation work to bring it up to modern standards.

At the same time I am willing to help out in any way that I can.

**Comment by kassane** [comment]
@awesomo4000 , @0x546F6D 

If I transfer the project to the @allyourcodebase community, would you support the project?

**Comment by 0x546F6D** [comment]
> If I transfer the project to the [@allyourcodebase](https://github.com/allyourcodebase) community, would you support the project?

I dont think that this repo can be transferred to [@allyourcodebase](https://github.com/allyourcodebase) since they solely focus on packaging C/C++ projects for the Zig build system, for repos that do not already have a build.zig/.zon upstream.

According to the [contribute](https://github.com/allyourcodebase#im-a-zig-user-and-i-want-to-contribute-a-repository-how-can-i-do-it) section of their readme, they do not accept binding/wrapper: 
> 2. Your repo must package the original C/C++ project without adding extra Zig-specific stuff like bindings, for example.
You are welcome to put bindings in a separate repo owned directly by you.

As you suggested, the best course of action might be to create an independent fork with @awesomo4000.

**Comment by jmcnamara** [comment]
> my build is a bit different and there are some verification tools in there for examining the excel files and screenshotting the outputs for ease of comparison.

@awesomo4000 

That is an interesting solution. Probably a slightly better approach would be to use the Excel comparison routines from the Python version of XlsxWriter: https://github.com/jmcnamara/XlsxWriter/blob/main/xlsxwriter/test/helperfunctions.py#L227

This unzips two xlsx files and compares the contents (apart from some transitory metadata like timestamps). It compares files created in Excel with files created with the library. In the test suite it is also used in the C libxlsxwriter library.

You could use that to compare target files you have from libxlsxwriter with files from the zig wrapper. That would make the tests a bit more cross platform.

**Comment by awesomo4000** [comment]
Thanks @jmcnamara  - that's a good idea. I would like to have a foolproof way to automatically verify. The only real definitive way to be very certain the produced spreadsheets were correct was by manual inspection for but good to know about that tool.

Here's the new zig-ified version I've been working on :

https://github.com/awesomo4000/excellent

I've been using an AI assistant to help with this. These are some instructions that it's following to help with new examples, verification, etc. (Also good for humans to read).

 https://github.com/awesomo4000/excellent/blob/main/docs/newhire.md

**Comment by awesomo4000** [comment]
> [@awesomo4000](https://github.com/awesomo4000) , [@0x546F6D](https://github.com/0x546F6D)
> 
> If I transfer the project to the [@allyourcodebase](https://github.com/allyourcodebase) community, would you support the project?

I think it's a good idea to put the "just the build" part in there certainly.
